"""ytdlp_release テーブルを追加

Revision ID: 01f4e2ff8faf
Revises: 9d2eee06a92a
Create Date: 2026-08-08 15:04:24.273225

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import sluicery.db.models

# revision identifiers, used by Alembic.
revision: str = '01f4e2ff8faf'
down_revision: str | Sequence[str] | None = '9d2eee06a92a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 手動整形: autogenerate は既存テーブルの CHECK 制約について「削除→再作成」の
    # 偽陽性 diff も出力していたため、実際の変更（ytdlp_release テーブル追加）に
    # 無関係な部分を取り除いた（既知の制限。docs/基本設計.md D-008）。
    op.create_table('ytdlp_release',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('installed_at', sluicery.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Enum('initial', 'manual', 'auto', name='ytdlp_release_source', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('installed', 'active', 'removed', name='ytdlp_release_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('activated_at', sluicery.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('deactivated_at', sluicery.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('smoketest_result_json', sa.JSON(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sluicery.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sluicery.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ytdlp_release')),
    sa.UniqueConstraint('version', name=op.f('uq_ytdlp_release_version'))
    )
    with op.batch_alter_table('ytdlp_release', schema=None) as batch_op:
        batch_op.create_index('ix_ytdlp_release_status', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ytdlp_release', schema=None) as batch_op:
        batch_op.drop_index('ix_ytdlp_release_status')

    op.drop_table('ytdlp_release')
    # ### end Alembic commands ###
