"""初期スキーマ

Revision ID: 9d2eee06a92a
Revises: 
Create Date: 2026-08-08 22:57:18.509476

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import sluicery.db.crypto
import sluicery.db.models


# revision identifiers, used by Alembic.
revision: str = '9d2eee06a92a'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sluicery.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('delivered_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_log'))
    )
    op.create_table('playlist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('folder_name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('kind_hint', sa.Enum('video', 'music', 'mixed', name='playlist_kind_hint', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('ytdlp_args', sa.String(length=4000), nullable=True),
    sa.Column('discover_cron', sa.String(length=100), nullable=True),
    sa.Column('download_cron', sa.String(length=100), nullable=True),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.Column('retention_policy_json', sa.JSON(), nullable=True),
    sa.Column('dedup_hardlink', sa.Boolean(), nullable=False),
    sa.Column('last_discover_at', sluicery.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_download_at', sluicery.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', sluicery.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sluicery.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_playlist'))
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('kind', sa.Enum('video', 'music', 'other', name='profile_kind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('ytdlp_args', sa.String(length=4000), nullable=True),
    sa.Column('format_selector', sa.String(length=1000), nullable=True),
    sa.Column('output_template', sa.String(length=1000), nullable=True),
    sa.Column('layout_strategy', sa.Enum('flat', 'custom', name='profile_layout_strategy', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('audio_extract', sa.Boolean(), nullable=False),
    sa.Column('audio_format', sa.String(length=50), nullable=True),
    sa.Column('audio_quality', sa.String(length=50), nullable=True),
    sa.Column('container', sa.String(length=50), nullable=True),
    sa.Column('embed_metadata', sa.Boolean(), nullable=False),
    sa.Column('embed_thumbnail', sa.Boolean(), nullable=False),
    sa.Column('embed_chapters', sa.Boolean(), nullable=False),
    sa.Column('subtitle_langs', sa.String(length=255), nullable=True),
    sa.Column('subtitle_auto', sa.Boolean(), nullable=False),
    sa.Column('subtitle_embed', sa.Boolean(), nullable=False),
    sa.Column('expert_mode', sa.Boolean(), nullable=False),
    sa.Column('allow_exec', sa.Boolean(), nullable=False),
    sa.Column('concurrent_fragments', sa.Integer(), nullable=True),
    sa.Column('postprocess_chain_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sluicery.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sluicery.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile'))
    )
    op.create_table('setting',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value_json', sa.String(), nullable=False),
    sa.Column('updated_at', sluicery.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_setting'))
    )
    op.create_table('storage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.Enum('local', 'remote', 'mount', name='storage_kind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('credentials_encrypted', sluicery.db.crypto.EncryptedJSON(), nullable=True),
    sa.Column('last_check_at', sluicery.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_check_result_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sluicery.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sluicery.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_storage'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('last_login_at', sluicery.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', sluicery.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sluicery.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('username', name=op.f('uq_user_username'))
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=2000), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('uploader', sa.String(length=500), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('upload_date', sa.String(length=20), nullable=True),
    sa.Column('playlist_index', sa.Integer(), nullable=True),
    sa.Column('membership', sa.Enum('active', 'delisted', name='item_membership', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('first_seen_at', sluicery.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sluicery.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('delisted_at', sluicery.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', sluicery.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sluicery.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], name=op.f('fk_item_playlist_id_playlist')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item')),
    sa.UniqueConstraint('playlist_id', 'source_id', name=op.f('uq_item_playlist_id'))
    )
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.create_index('ix_item_playlist_id_membership', ['playlist_id', 'membership'], unique=False)
        batch_op.create_index('ix_item_source_id', ['source_id'], unique=False)

    op.create_table('playlist_profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('storage_id', sa.Integer(), nullable=False),
    sa.Column('subpath', sa.String(length=1000), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sluicery.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sluicery.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], name=op.f('fk_playlist_profile_playlist_id_playlist')),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], name=op.f('fk_playlist_profile_profile_id_profile')),
    sa.ForeignKeyConstraint(['storage_id'], ['storage.id'], name=op.f('fk_playlist_profile_storage_id_storage')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_playlist_profile')),
    sa.UniqueConstraint('playlist_id', 'profile_id', name=op.f('uq_playlist_profile_playlist_id'))
    )
    op.create_table('run',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trigger', sa.Enum('manual', 'schedule', 'api', name='run_trigger', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('running', 'succeeded', 'failed', 'cancelled', name='run_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('started_at', sluicery.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sluicery.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('stats_json', sa.JSON(), nullable=True),
    sa.Column('log_path', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], name=op.f('fk_run_playlist_id_playlist')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_run'))
    )
    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.create_index('ix_run_started_at', ['started_at'], unique=False)

    op.create_table('target',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('playlist_profile_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'queued', 'downloading', 'processing', 'downloaded', 'failed', 'unavailable', 'blocked', 'missing', 'ignored', name='target_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=4000), nullable=True),
    sa.Column('last_attempt_at', sluicery.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('blocked_reason', sa.String(length=1000), nullable=True),
    sa.Column('downloaded_at', sluicery.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', sluicery.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sluicery.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name=op.f('fk_target_item_id_item'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['playlist_profile_id'], ['playlist_profile.id'], name=op.f('fk_target_playlist_profile_id_playlist_profile')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_target')),
    sa.UniqueConstraint('item_id', 'playlist_profile_id', name=op.f('uq_target_item_id'))
    )
    with op.batch_alter_table('target', schema=None) as batch_op:
        batch_op.create_index('ix_target_playlist_profile_id_status', ['playlist_profile_id', 'status'], unique=False)
        batch_op.create_index('ix_target_status', ['status'], unique=False)

    op.create_table('task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Enum('discover', 'download', 'verify', 'postprocess', 'publish', 'index', 'integrity_check', 'retention', 'update_ytdlp', name='task_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('target_ref_type', sa.String(length=50), nullable=False),
    sa.Column('target_ref_id', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('worker_class', sa.Enum('network', 'compute', name='task_worker_class', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'queued', 'running', 'succeeded', 'failed', 'cancelled', name='task_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('depends_on_task_id', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sluicery.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('started_at', sluicery.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sluicery.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(length=4000), nullable=True),
    sa.Column('log_excerpt', sa.String(length=4000), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sluicery.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_task_id'], ['task.id'], name=op.f('fk_task_depends_on_task_id_task')),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], name=op.f('fk_task_run_id_run')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task'))
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index('ix_task_depends_on_task_id', ['depends_on_task_id'], unique=False)
        batch_op.create_index('ix_task_status_worker_class_priority', ['status', 'worker_class', 'priority'], unique=False)

    op.create_table('artifact',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('source', 'derived', name='artifact_role', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('storage_id', sa.Integer(), nullable=False),
    sa.Column('relative_path', sa.String(length=2000), nullable=False),
    sa.Column('absolute_path_cache', sa.String(length=2000), nullable=True),
    sa.Column('container', sa.String(length=50), nullable=True),
    sa.Column('format_id', sa.String(length=100), nullable=True),
    sa.Column('video_codec', sa.String(length=100), nullable=True),
    sa.Column('audio_codec', sa.String(length=100), nullable=True),
    sa.Column('filesize', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=255), nullable=True),
    sa.Column('produced_by_task_id', sa.Integer(), nullable=True),
    sa.Column('verified_at', sluicery.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('missing_since', sluicery.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', sluicery.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sluicery.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['produced_by_task_id'], ['task.id'], name=op.f('fk_artifact_produced_by_task_id_task')),
    sa.ForeignKeyConstraint(['storage_id'], ['storage.id'], name=op.f('fk_artifact_storage_id_storage')),
    sa.ForeignKeyConstraint(['target_id'], ['target.id'], name=op.f('fk_artifact_target_id_target'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifact'))
    )
    with op.batch_alter_table('artifact', schema=None) as batch_op:
        batch_op.create_index('ix_artifact_storage_id', ['storage_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artifact', schema=None) as batch_op:
        batch_op.drop_index('ix_artifact_storage_id')

    op.drop_table('artifact')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index('ix_task_status_worker_class_priority')
        batch_op.drop_index('ix_task_depends_on_task_id')

    op.drop_table('task')
    with op.batch_alter_table('target', schema=None) as batch_op:
        batch_op.drop_index('ix_target_status')
        batch_op.drop_index('ix_target_playlist_profile_id_status')

    op.drop_table('target')
    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.drop_index('ix_run_started_at')

    op.drop_table('run')
    op.drop_table('playlist_profile')
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_index('ix_item_source_id')
        batch_op.drop_index('ix_item_playlist_id_membership')

    op.drop_table('item')
    op.drop_table('user')
    op.drop_table('storage')
    op.drop_table('setting')
    op.drop_table('profile')
    op.drop_table('playlist')
    op.drop_table('event_log')
    # ### end Alembic commands ###
